export const CLASSES = [
    {subject: "Humanities Core: World History", id: 1},
    {subject: "Honors Humanities Core: World History", id: 2},
    {subject: "World History Sheltered", id: 3},
    {subject: "Humanities Core: US History", id: 4},
    {subject: "Honors Humanities Core: US History", id: 5},
    {subject: "American Government", id: 6},
    {subject: "Model United Nations: American Government", id: 7},
    {subject: "AP World History", id: 8},
    {subject: "AP US History", id: 9},
    {subject: "AP American Government", id: 10},
    {subject: "Humanities Core: World Literature", id: 11},
    {subject: "Honors Humanities Core: World Literature", id: 12},
    {subject: "Introduction to English", id: 13},
    {subject: "Humanities Core: US Literature", id: 14},
    {subject: "Honors Humanities Core: US Literature", id: 15},
    {subject: "European Literature", id: 16},
    {subject: "Honors European Literature", id: 17},
    {subject: "Honors Critical Theory and Literature", id: 18},
    {subject: "Contemporary Literature", id: 19},
    {subject: "Film & Literature", id: 20},
    {subject: "Science Fiction", id: 21},
    {subject: "AP English Literature & Composition", id: 22},
    {subject: "Math I", id: 23},
    {subject: "Math II", id: 24},
    {subject: "Enhanced Math II", id: 25},
    {subject: "Math III", id: 26},
    {subject: "Enhanced Math III", id: 27},
    {subject: "Math 4", id: 28},
    {subject: "AP Pre-Calculus", id: 29},
    {subject: "AP Statistics", id: 30},
    {subject: "AP Computer Science A", id: 31},
    {subject: "Integrated Science 1", id: 32},
    {subject: "Honors Integrated Science 1", id: 33},
    {subject: "Integrated Science 2", id: 34},
    {subject: "Honors Integrated Science 2", id: 35},
    {subject: "Integrated Science 3", id: 36},
    {subject: "Honors Integrated Science 3", id: 37},
    {subject: "Anatomy & Physiology", id: 38},
    {subject: "Marine Science", id: 39},
    {subject: "Principles of Engineering", id: 40},
    {subject: "Geology", id: 41},
    {subject: "Honors Geology", id: 42},
    {subject: "Honors Forensic Science", id: 43},
    {subject: "Honors Interdisciplinary Climate Explorations (ICE)", id: 44},
    {subject: "AP Biology", id: 45},
    {subject: "AP Chemistry", id: 46},
    {subject: "AP Physics 1", id: 47},
    {subject: "AP Environmental Science", id: 48},
    {subject: "AP Computer Science Principles", id: 49},
    {subject: "Computer Science Data Structures", id: 50},
    {subject: "American Sign Language 1", id: 51},
    {subject: "American Sign Language 2", id: 52},
    {subject: "American Sign Language 3", id: 53},
    {subject: "Honors American Sign Language 4", id: 54},
    {subject: "French 1", id: 55},
    {subject: "French 2", id: 56},
    {subject: "French 3", id: 57},
    {subject: "Honors French 4", id: 58},
    {subject: "Korean 1", id: 59},
    {subject: "Korean 2", id: 60},
    {subject: "Korean 3", id: 61},
    {subject: "Spanish 1", id: 62},
    {subject: "Spanish 2", id: 63},
    {subject: "Spanish 3", id: 64},
    {subject: "Honors Spanish 4", id: 65},
    {subject: "AP Spanish Language and Culture", id: 66},
    {subject: "Dance Tech 1", id: 67},
    {subject: "Dance Tech 2", id: 68},
    {subject: "Dance Tech 3", id: 69},
    {subject: "Dance Theater", id: 70},
    {subject: "Bass Clef", id: 71},
    {subject: "Bel Canto", id: 72},
    {subject: "Chamber Singers", id: 73},
    {subject: "Concert Band", id: 74},
    {subject: "Concert Chorale", id: 75},
    {subject: "Concert Orchestra", id: 76},
    {subject: "Guitar Studio", id: 77},
    {subject: "Guitar 2", id: 78},
    {subject: "Jazz Ensemble 1", id: 79},
    {subject: "Jazz Ensemble 2", id: 80},
    {subject: "Jazz Ensemble 3", id: 81},
    {subject: "Jazz Ensemble 4", id: 82},
    {subject: "Music Theory", id: 83},
    {subject: "AP Music Theory", id: 84},
    {subject: "Philharmonic Orchestra", id: 85},
    {subject: "String Orchestra", id: 86},
    {subject: "Symphonic Band", id: 87},
    {subject: "Symphonic Orchestra", id: 88},
    {subject: "Treble Clef", id: 89},
    {subject: "Viva Cantar", id: 90},
    {subject: "Wind Ensemble", id: 91},
    {subject: "Wind Symphony", id: 92},
    {subject: "Creative Drama", id: 93},
    {subject: "Intermediate Drama", id: 94},
    {subject: "Advanced Drama", id: 95},
    {subject: "Technical Theater", id: 96},
    {subject: "Advanced Technical Theater", id: 97},
    {subject: "Introduction to Art", id: 98},
    {subject: "Painting/Drawing", id: 99},
    {subject: "Art Portfolio Prep", id: 100},
    {subject: "AP Studio Art: Drawing", id: 101},
    {subject: "AP Art History", id: 102},
    {subject: "Beginning Ceramics", id: 103},
    {subject: "Intermediate Ceramics", id: 104},
    {subject: "Advanced Ceramics", id: 105},
    {subject: "Computer Graphic Art", id: 106},
    {subject: "AP Studio Art: 2-D Design", id: 107},
    {subject: "Beginning Screen Printing & Design", id: 108},
    {subject: "Video Production", id: 109},
    {subject: "Art of TV/Video", id: 110},
    {subject: "Visual Imagery (Photography)", id: 111},
    {subject: "Advanced Visual Imagery", id: 112},
    {subject: "ROP Broadcast News (NTV)", id: 113},
    {subject: "3-D Animation & Design", id: 114},
    {subject: "Advanced Creative Writing", id: 115},
    {subject: "Advanced Culinary Arts", id: 116},
    {subject: "Anthropology (semester)", id: 117},
    {subject: "Beginning Journalism", id: 118},
    {subject: "Business Communications", id: 119},
    {subject: "Careers in Education 1", id: 120},
    {subject: "Careers in Education 2", id: 121},
    {subject: "Careers with Children (Internship) (semester)", id: 122},
    {subject: "Creative Writing 1", id: 123},
    {subject: "Creative Writing 2", id: 124},
    {subject: "Economics of Business (semester)", id: 125},
    {subject: "Honors Political Economy (semester)", id: 126},
    {subject: "Intermediate Computer Graphics", id: 127},
    {subject: "Intro to Culinary Arts", id: 128},
    {subject: "Model United Nations: International", id: 129},
    {subject: "NHS Newspaper (Howler)", id: 130},
    {subject: "Psychology (semester)", id: 131},
    {subject: "Honors Forensic Psychology", id: 132},
    {subject: "World Religions (semester)", id: 133},
    {subject: "Model United Nations", id: 134},
  ];

export const DAYSINWEEK = ["S", "M", "T", "W", "T", "F", "S"];